name: intake-xarray
channels:
- intake
- conda-forge
- defaults
dependencies:
- apipkg=1.4=py36_0
- astroid=1.6.3=py36_0
- attrs=17.4.0=py_0
- autopep8=1.3.4=py_0
- ciocheck=0.1.1=py36_1
- coverage=4.5.1=py36_0
- execnet=1.5.0=py_0
- flake8=3.5.0=py36_0
- isort=4.3.4=py36_0
- lazy-object-proxy=1.3.1=py36_0
- mccabe=0.6.1=py36_0
- more-itertools=4.1.0=py_0
- pluggy=0.6.0=py_0
- py=1.5.3=py_0
- pycodestyle=2.3.1=py36_0
- pydocstyle=2.1.1=py36_0
- pyflakes=1.6.0=py36_0
- pylint=1.8.4=py36_0
- pytest=3.5.0=py36_0
- pytest-cov=2.5.1=py36_0
- pytest-forked=0.2=py36_0
- pytest-json=0.4.0=py36_0
- pytest-xdist=1.22.2=0
- snowballstemmer=1.2.1=py36_0
- wrapt=1.10.11=py36_0
- yapf=0.21.0=py_0
- appdirs=1.4.3=py36_0
- asn1crypto=0.24.0=py36_0
- bokeh=0.12.14=py36_0
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2018.1.18=py36_0
- cffi=1.11.5=py36h342bebf_0
- chardet=3.0.4=py36h96c241c_1
- click=6.7=py36hec950be_0
- cloudpickle=0.5.2=py36_1
- cryptography=2.2.1=py36h1de35cc_0
- cytoolz=0.9.0.1=py36h1de35cc_0
- dask=0.17.2=py36_0
- dask-core=0.17.2=py36_0
- distributed=1.21.4=py36_0
- heapdict=1.0.0=py36_2
- idna=2.6=py36h8628d0a_1
- intel-openmp=2018.0.0=8
- jinja2=2.10=py36hd36f9c5_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- libgfortran=3.0.1=h93005f0_2
- locket=0.2.0=py36hca03003_1
- markupsafe=1.0=py36h3a1e703_1
- mkl=2018.0.2=1
- msgpack-numpy=0.4.3=py36_0
- msgpack-python=0.5.5=py36h04f5b5a_0
- ncurses=6.0=hd04f020_2
- numpy=1.14.2=py36ha9ae307_0
- openssl=1.0.2n=hdbc3d79_0
- packaging=17.1=py36_0
- partd=0.3.8=py36hf5c4cb8_0
- pip=9.0.1=py36_5
- psutil=5.4.3=py36h1de35cc_0
- pycparser=2.18=py36h724b2fc_1
- pyopenssl=17.5.0=py36h51e4350_0
- pyparsing=2.2.0=py36hb281f35_0
- pysocks=1.6.8=py36_0
- python=3.6.4=hc167b69_3
- python-dateutil=2.7.0=py36_0
- python-snappy=0.5.1=py36_0
- pytz=2018.3=py36_0
- pyyaml=3.12=py36h2ba1e63_1
- readline=7.0=hc1231fa_4
- requests=2.18.4=py36h4516966_1
- ruamel_yaml=0.15.35=py36h1de35cc_1
- scipy=1.0.0=py36h1de22e9_0
- setuptools=38.5.1=py36_0
- six=1.11.0=py36h0e22d5e_1
- snappy=1.1.7=he62c110_3
- sortedcontainers=1.5.9=py36_0
- sqlite=3.22.0=h3efe00b_0
- tblib=1.3.2=py36hda67792_0
- tk=8.6.7=h35a86e2_3
- toolz=0.9.0=py36_0
- tornado=5.0=py36_0
- urllib3=1.22=py36h68b9469_0
- wheel=0.30.0=py36h5eb2c71_1
- xz=5.2.3=h0278029_2
- yaml=0.1.7=hc338f04_2
- zict=0.1.3=py36h71da714_0
- zlib=1.2.11=hf3cbc9b_2
- intake=0.0.2=py_196
- pandas=0.23.0=py36h39e3cac_0
- pip:
  - holoviews==1.9.5
  - msgpack==0.5.6
  - param==1.5.1
  - ruamel-yaml==0.15.35
  - ruamel.yaml==0.15.37
  - xarray==0.10.2
