name: test_env
channels:
  - conda-forge
dependencies:
  - python==3.10
  - aiohttp
  - exifread
  - flask
  - h5netcdf
  - netcdf4
  - pip
  - pydap
  - pytest
  - rangehttpserver
  - rasterio
  - s3fs
  - scikit-image
  - entrypoints
  - pandas
  - tornado
  - zarr
  - moto < 3
  - intake
  - rioxarray
  - gdal
  - pip:
       - git+https://github.com/fsspec/filesystem_spec.git
       - git+https://github.com/intake/intake.git
       - git+https://github.com/pydata/xarray.git
