name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - aiohttp
  - boto3
  - exifread
  - flask
  - h5netcdf
  - intake
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - s3fs >= 2021.08.0
  - scikit-image
  - xarray >= 0.17
  - rangehttpserver
  - zarr
  - moto < 3
  - s3fs
  - werkzeug < 2.2.0
