name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - aiohttp
  - boto3
  - exifread
  - flask
  - h5netcdf
  - intake
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - s3fs >= 2021.08.0
  - scikit-image
  - rangehttpserver
  - xarray >= 0.17
  - zarr
  - pip:
       - moto[s3]==1
