name: test_env
channels:
  - conda-forge
dependencies:
  - python==3.9
  - aiohttp
  - boto3
  - flask
  - h5netcdf
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - scikit-image
  - zarr
  - s3fs
  - moto
  - pip:
       - git+https://github.com/fsspec/filesystem_spec.git
       - git+https://github.com/intake/intake.git
       - git+https://github.com/pydata/xarray.git
       - rangehttpserver
