name: test_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - intake>=0.4.1
  - xarray=0.11.0  # pinnned this low as a test
  - zarr
  - pytest
  - netcdf4
  - rasterio
  - scikit-image
  - fsspec